@startuml

interface SistemaDeTurnos {
    + finalizarTurno(): void
    + perderTurnos(): void
    + habilitar(): boolean
}

interface SistemaDeDefensa {
    + recibirDanio(energia: Energia): void
    + defenderse(): void
    + equipar(): void
    + esEquipoMaximo(): boolean
}

interface JugadorGanador {
    + yoSoy(): String
}

Jugador ..|> SistemaDeTurnos
Jugador ..|> SistemaDeDefensa
Jugador ..|> JugadorGanador

abstract class Jugador {
    # energia: Energia
    # d: DispositivoDeAzar
    # turno: Turno
    # nombre: String
    # mapa: Mapa

    + afectarEnergia(energia: Energia): void
    + habilitar(): boolean
    + lanzar(): ValorAzar
    + yoSoy(): String
    + ingresar(mapa: Mapa): void
    + miDescripcion(): String
    + {abstract} moverse(): void
    + {abstract} finalizarTurno(): void

}

@enduml