@startuml GladiadorConCascoEncuentraEquipamiento

participant Habilitado as ":Habilitado"
participant Gladiador as ":Gladiador"

participant Casillero as ":Casillero"
participant Equipamiento as ":Equipamiento"

participant Casco as ":Casco"

Habilitado -> Casillero: entregarElementos(Gladiador)
Casillero -> Equipamiento: interactuar(Gladiador)

Equipamiento -> Gladiador: equipar()
Gladiador -> Casco: mejorar()
create Armadura as ":Armadura"
Casco -> Armadura: <<create>>
Casco --> Gladiador: Armadura

@enduml