@startuml gladiadorConCascoEncuentraUnaFiera

participant Habilitado as ":Habilitado"
participant Gladiador as ":Gladiador"

participant Casillero as ":Casillero"
participant Fiera as ":Fiera"

participant Casco as ":Casco"
participant energiaGladiador as "energiaGladiador:Energia"

Habilitado -> Casillero: entregarElementos(Gladiador)
Casillero -> Fiera: interactuar(Gladiador)

Fiera -> Gladiador: defenderse()
Gladiador -> Casco: recibirDanio(energiaGladiador)
Casco -> energiaGladiador: afectarEnergia(Energia(-15))


@enduml