@startuml

actor Usuario

create MapaLineal
Usuario ->> MapaLineal: m = new MapaLineal()
create Tablero
Usuario ->>  Tablero: t = new Tablero(m)
create AlgoRoma
Usuario ->>  AlgoRoma: algoRoma = new AlgoRoma(t)
create ListaCircular
AlgoRoma ->>  ListaCircular: new()
create MockDado
Usuario ->> MockDado: new()

create Gladiador
Usuario ->>  Gladiador: new Gladiador("Espartaco")
Usuario -> Gladiador: agregarDispositivoAzar(MockDado)

Usuario -> AlgoRoma: agregarJugador(Gladiador)
AlgoRoma -> Tablero: posicionInicial()
Tablero -> MapaLineal: obtenerPosicionInicial()
MapaLineal --> Tablero: PosicionLineal(0)
Tablero --> AlgoRoma: PosicionLineal(0)

create Posicion
AlgoRoma -> Posicion: PosicionLineal(0)
AlgoRoma -> Gladiador: posicionar(Posicion)
AlgoRoma -> ListaCircular: agregarElemento(Gladiador)


@enduml