@startuml entregarElementosDeUnCasilleroAUnJugador

actor Usuario
Usuario -> AlgoRoma: entregarElementos(Gladiador)
AlgoRoma -> Gladiador: miPosicion()
Gladiador --> AlgoRoma: Posicion
AlgoRoma -> Tablero: obtenerCasillero(Posicion)
Tablero -> Mapa: obtenerCasillero(Posicion)
Mapa --> Tablero: Casillero
Tablero --> AlgoRoma: Casillero
AlgoRoma -> Casillero: entregarElementos(Gladiador)
Casillero -> Interactuable: interactuar(jugador)


@enduml