@startuml

actor Usuario
Usuario -> AlgoRoma: finalizarTurno()
AlgoRoma -> Gladiador: finalizarTurno()
Gladiador -> Turno: finalizar()
Gladiador -> Seniority: aumentarEnergia
Gladiador -> Gladiador: ascenderSeniority
Gladiador -> Seniority: ascenderSeniority

alt turnos!=0
    Gladiador -> Gladiador: sumarUnTurno()
end

Gladiador -> Jugadores: siguiente()
Jugadores -> Gladiador: jugadorActual

alt turnos == 0  && noHayGanador
    Gladiador -> Gladiador: finalizarJuego(Jugador)
end

@enduml