@startuml

actor Usuario
create InformacionMapaEnMatriz
Usuario -> InformacionMapaEnMatriz: InformacionMapaEnMatriz(elementosMapa)
create MapaLineal
Usuario -> MapaLineal: MapaLineal(informacionMapaEnMatriz)
MapaLineal -> InformacionMapaEnMatriz: construirCasilleros()
create "casilleros" << LinkedList >>
InformacionMapaEnMatriz -> casilleros: new()
create CasilleroMapa
loop i < elementosMapa.length
    InformacionMapaEnMatriz -> CasilleroMapa: new()
    loop j < elementosMapa[i].length
        InformacionMapaEnMatriz -> CasilleroMapa: recibirElemento(elementosMapa[i][j])
    end
    InformacionMapaEnMatriz -> casilleros: add(casilleroMapa)
end
InformacionMapaEnMatriz --> MapaLineal: casilleros

@endum