@startuml

actor ACTOR
participant AlgoRoma
participant Jugador1 as "Espartaco: Jugador"
participant Jugador2 as "Caroforo: Jugador"

create Jugador1
ACTOR -> Jugador1: Espartaco = new Gladiador("Espartaco")
create Jugador2
ACTOR -> Jugador2: Carpoforo = new Gladiador("Carpoforo")

ACTOR -> AlgoRoma: agregarJugador(Espartaco)
ACTOR -> AlgoRoma: agregarJugador(Carpoforo)


ACTOR -> AlgoRoma: iniciarPartida()
AlgoRoma --> ACTOR: jugador

ACTOR -> Jugador1: moverse()
Jugador1 -> Turno: estaHabilitado()
Turno --> Jugador1: t = true
Jugador1 -> Energia: tengoEnergia()
Energia --> Jugador1: e = true

Jugador1 -> Mapa: moverJugador(this.casillero,this)

Mapa -> Mapa: casilleroNuevo = calculaNuevoCasillero
Mapa -> Jugador1: posicionar(casilleroNuevo)
Jugador1 -> Jugador1: this.casillero = casilleroNuevo
@enduml