@startuml

actor ACTOR
create InformacionMapa

ACTOR -> InformacionMapa
create Mapa
ACTOR -> Mapa: mapa = new Mapa(InformacionMapa)

Create AlgoRoma
ACTOR -> AlgoRoma: algoRoma = new AlgoRoma(mapa)


create Jugador

ACTOR -> Jugador: Espartaco = new Gladiador("Espartaco")
ACTOR -> Jugador: Carpoforo = new Gladiador("Carpoforo")

ACTOR -> AlgoRoma: agregarJugador(Espartaco)
ACTOR -> AlgoRoma: agregarJugador(Carpoforo)


ACTOR -> AlgoRoma: iniciarPartida()
AlgoRoma --> ACTOR: jugador

ACTOR -> Jugador: moverse()
Jugador -> Turno: estaHabilitado()
Turno --> Jugador: t = true
Jugador -> Energia: tengoEnergia()
Energia --> Jugador: e = true

Jugador -> Mapa: moverJugador(this.casillero,this)

Mapa -> Mapa: casilleroNuevo = calculaNuevoCasillero
Mapa -> Jugador: posicionar(casilleroNuevo)
@enduml