@startuml

actor ACTOR
participant AlgoRoma
participant Jugador1 as "Espartaco: Jugador"
participant Jugador2 as "Carpoforo: Jugador"

create Jugador1
ACTOR -> Jugador1: Espartaco = new Gladiador("Espartaco")

create Jugador2
ACTOR -> Jugador2: Carpoforo = new Gladiador("Carpoforo")

ACTOR -> AlgoRoma: agregarJugador(Espartaco)
ACTOR -> AlgoRoma: agregarJugador(Carpoforo)


ACTOR -> AlgoRoma: comenzarPartida()
AlgoRoma --> ACTOR: jugador

ACTOR -> Mapa: obtenerProximoDestino(jugador)
Mapa -> Jugador: lanzar()
Jugador -> DispositivoDeAzar: lanzar()
DispositivoDeAzar --> Jugador: ValorAzar
Jugador --> Mapa: ValorAzar
Mapa --> ACTOR: casillero

ACTOR -> Jugador1: moverse(casillero)
Jugador1 -> Turno: estaHabilitado()
Turno --> Jugador1: True
Jugador1 -> Energia: tengoEnergia()
Energia --> Jugador1: False
Jugador1 -> Energia: afectarEnergia(new Energia(5))
Jugador1 -> Turno: deshabilitar()

@enduml