@startuml

actor ACTOR
participant AlgoRoma
participant Jugador1 as "Espartaco: Gladiador"
participant Jugador2 as "Carpoforo: Gladiador"

create Jugador1
ACTOR -> Jugador1: Espartaco = new Gladiador("Espartaco")
create Jugador2
ACTOR -> Jugador2: Carpoforo = new Gladiador("Carpoforo")


ACTOR -> AlgoRoma: agregarJugador(Espartaco)
ACTOR -> AlgoRoma: agregarJugador(Carpoforo)


ACTOR -> AlgoRoma: iniciarPartida()
AlgoRoma --> ACTOR: jugador

ACTOR -> Jugador1: moverse()

ACTOR -> Jugador1: obtenerElementos()

Jugador1 -> Casillero: entregarElementos(this)

alt para cada elemento
    Casillero -> ElementoMapa: interactuar(jugador)
    ElementoMapa -> Jugador1: interactuar()

end

@enduml