@startuml

actor ACTOR
create InformacionMapa
ACTOR -> InformacionMapa
create Mapa
ACTOR -> Mapa: mapa = new Mapa(InformacionMapa)

Create AlgoRoma
ACTOR -> AlgoRoma: algoRoma = new AlgoRoma(mapa)


create EnergiaJugador
create Jugador
ACTOR -> Jugador: Espartaco = new Gladiador("Espartaco")
ACTOR -> Jugador: Carpoforo = new Gladiador("Carpoforo")

ACTOR -> AlgoRoma: agregarJugador(Carpoforo)
ACTOR -> AlgoRoma: agregarJugador(Espartaco)

ACTOR -> AlgoRoma: iniciarPartida()
AlgoRoma --> ACTOR: jugador

ACTOR -> Jugador: moverse()
ACTOR -> Jugador: obtenerElementos()

Jugador -> Casillero: entregarElementos(this)

Casillero -> Fiera: interacturar(jugador)

create Energia
Fiera -> Energia: e = new Energia(-20)
Fiera -> Jugador: defenderse(e)

Jugador -> Turno: estaHabilitado()
Turno --> Jugador: true

Jugador -> EnergiaJugador: afetarEnergia(e)

ACTOR -> Energia: esperada = new Energia(0)

ACTOR -> Jugador: compararEnergia(esperada)

Jugador --> ACTOR: true



@enduml