@startuml Jugador

abstract class Jugador{
    -nombre: String
    +afectarEnergia(energia: Energia)
    +compararSalud(energia: Energia)
    +compararEquipo(equipamiento: Equipamiento)
    +modificarEquipo(equipo: Equipo)
    +posicionar(posicion: Posicion)
    +miPosicion(): Posicion()
    +habilitar()
    +estaHabilitado(): boolean
    +deshabilitar()
    +{abstract}perderTurnos()
    +agregarDispositivoAzar(dispositivoDeAzar: DispositivoDeAzar)
    +lanzar(): ValorAzar
}


interface SistemaDefensa{
    +{abstract}recibirDanio(Energia energia)
    +{abstract}modificarEquipo(equipo: Equipo)
    +{abstract}compararEquipo(equipamiento: Equipamiento): boolean
    +{abstract}defenderse()
}

interface SistemaPosicionamiento{
    +{abstract}moverse(tablero: Tablero)
    +{abstract}posicionar(posicion: Posicion)
    +{abstract}miPosicion(): Posicion
}

interface SistemaTurnos{
    +{abstract}finalizarTurno()
    +{abstract}perderTurnos(turno: Turno)
    +{abstract}habilitar()
    +{abstract}deshabilitar()
    +{abstract}estaHabilitado()
}


class Energia{
    -disponible: int
    +Energia(disponible: int)
    +afectarEnergia(energia: Energia)
    +otorgarEnergia(): int
    +tengoEnergia(): boolean
    +comparar(energia: Energia): boolean
    #cantidadeEnergia(): int
}


interface Posicion{
    +{abstract}cambiarPosicion(posicion: Posicion): Posicion
    +{abstract}obtenerCoordenada(): Coordenada
    +{abstract}esIgual(posicion: Posicion): boolean
    +{abstract}esMayorIgual(posicion: Posicion): boolean
}


abstract class Equipo{
    -tipoEquipo: Equipamiento
    +interactuo: boolean
    +interactuar(jugador: Jugador)
    +{abstract}energiaAReducir(): Energia
    +puedoEquipar(equipo: Equipo): boolean
    +esPremio(): boolean
    +interactuo(): boolean
    +equipoEsEquipado()
    +comparar(equipo: Equipo): boolean
}


interface DispositivoDeAzar{
    +{abstract}lanzar(): ValorAzar
}


class Turno{
    -cantidad: int
    -habilitado: int
    +Turno(cantidad: int)
    +habilitar()
    +deshabilitar()
    +estaHabilitado(): boolean
    +finalizar()
    +esMayor(turno: Turno): boolean
    +perderTurnos(turnos: Turno)
}


class Gladiador{
    +Gladiador(nombre: String)
    +ascenderSeniority()
    +moverse(tablero: Tablero)
    +perderTurnos()
    +finalizarTurno()
    +recibirDanio(energia: Energia
    +defenderse()
}

SistemaDefensa <|.. Jugador
SistemaPosicionamiento <|.. Jugador
SistemaTurnos <|.. Jugador

SistemaPosicionamiento -[hidden]> SistemaDefensa


Gladiador --|> Jugador

Gladiador -[hidden]> Jugador


Jugador --> Energia
Jugador ---> Posicion
Jugador --> Equipo
Jugador ---> DispositivoDeAzar
Jugador --> Turno

@enduml