@startuml MapaLineal

class MapaLineal{
    +MapaLineal(informacionMapa: InformacionMapa)
    +obtenerCasillero(posicion Posicion): Casillero
    +calcularPosicion(valor: ValorAzar): PosicionLineal
    +obtenerPosicionInicial(): Posicion
    +obtenerPosicionFinal(): Posicion
    +obtenerPosicionDelMedio(): Posicion
}


interface Posicion{
    +{abstract}cambiarPosicion(posicion: Posicion): Posicion
    +{abstract}obtenerCoordenada(): Coordenada
    +{abstract}esIgual(posicion: Posicion): boolean
    +{abstract}esMayorIgual(posicion: Posicion): boolean
}

class PosicionLineal{
    +PosicionLineal(int x)
    +cambiarPosicion(posicion: Posicion): Posicion
    +obtenerCoordenada(): Coordenada
    +esIgual(posicion: Posicion): boolean
    +esMayorIgual(posicion: Posicion): boolean
}

class Coordenada{
    -valor: int
    +Coordenada(c: int)
    +valor(): int
    +moverCoordenada(c: Coordenada)
}


interface Casillero{
    +{abstract}entregarElementos(Jugador jugador)
}

class CasilleroMapa{
    +recibirElemento(elemento: Interactuable)
    +entregarElementos(jugador: Jugador)
}

class LinkedList<E> <<Java Class>>{
}

class Interactuable{
    +{abstract}interactuar (jugador: Jugador)
    +{abstract}esPremio(): boolean
    +{abstract}interactuo(): boolean
}


interface ConstructorMapa{
    +{abstract}construirMapa(datos: Map<Posicion, Casillero>, casilleros: LinkedList<Casillero>)
}

class ConstructorLineal{
    +construirMapa(datos: Map<Posicion, Casillero>, casilleros: LinkedList<Casillero>)
}


interface InformacionMapa{
    +{abstract}construirCasilleros(): LinkedList<Casillero>
}

class InformacionMapaEnMatriz{
    -informacionMapa: Interactuable[][]
    +InformacionMapaEnMatriz(informacion: Interactuable[][])
    +construirCasillero(): LinkedList<Casillero>
}



MapaLineal " 1" --> "*" Posicion
MapaLineal "1" --> "*" Casillero
MapaLineal ----> ConstructorMapa

Posicion - Casillero

MapaLineal ..> InformacionMapa

Posicion <|-- PosicionLineal

Casillero <|-- CasilleroMapa

ConstructorMapa <|-- ConstructorLineal

InformacionMapa <|-- InformacionMapaEnMatriz

PosicionLineal --> Coordenada

CasilleroMapa --> LinkedList
LinkedList "1" --> "*" Interactuable


@enduml