@startuml

interface Seniority {
    + ascenderSeniority(): Seniority
    + aumentarEnergia(): void
    + descripcion(): String
}

Gladiador ----> Seniority
Gladiador ---> Equipo
abstract class Equipo {
    + mejorar(): Equipo
    + recibirDanio (energia: Energia): void
    + sePuedeMejorar(): boolean
    
}
abstract class Jugador {
}
Jugador <|- Gladiador
class Gladiador {

    + Gladiador(nombre: String)
    + ascenderSeniority(): void
    + moverse(): void
    + obtenerElementos(): void
    + perderTurnos(turnos: Turno): void
    + finalizarTurno(algoRoma: AlgoRoma): void
    + recibirDanio(energia: Energia): void
    + defenderse(): void
    + equiar(): void
    + esEquipoMaximo(): boolean
    + miDescripcion(): String

}

@enduml