@startuml Gladiador

class Gladiador {
    +Gladiador(nombre: String)
    +moverse(mapa: Mapa)
    +defenderse()
    +equipar()
    +esEquipoMaximo(): boolean
    +compararEquipo(equipo: JerarquiaEquipos): boolean
    +miDescripcion(): String
}

interface Seniority{
    +{abstract} ascenderSeniority(turno: Turno): Seniority
    +{abstract} aumentarEnergia(energia: Energia)
    +{abstract} description(): String
}

abstract class Equipo{
    -jerarquia: JerarquiaEquipos
    +{abstract}mejorar(): Equipo
    +{abstract}recibirDanio()
    +sePuedeMejorar(): boolean
    +compararEquipo(equipamiento: JerarquiaEquipos): boolean
    +{abstract} descripcion(): String
}

Gladiador <|-- Seniority
Gladiador <|-- Equipo


@enduml